version: '2'
services:
    erpproduction-app:
        image: erpproduction
        external_links:
            - erpproduction-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/erpproduction?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    erpproduction-mysql:
        extends:
            file: mysql.yml
            service: erpproduction-mysql
